name: APK Oluşturucu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3

      - name: Node.js Kur
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Bubblewrap ve Gereksinimleri Kur
        run: |
          npm install -g @bubblewrap/cli
          mkdir -p ~/.bubblewrap
          # Gerekli ayarları önceden oluşturarak soru sormasını engelliyoruz
          echo '{"jdkPath":"/usr/lib/jvm/java-11-openjdk-amd64","androidSdkPath":"/usr/local/lib/android/sdk"}' > ~/.bubblewrap/config.json

      - name: APK Paketle
        run: |
          # Soru sormaması için tüm ayarları komut satırından veriyoruz
          bubblewrap init --manifest=manifest.json --metaData='{"no_prompt":true}' --now
          bubblewrap build --skipSigning
          
      - name: APK Dosyasını Kaydet
        uses: actions/upload-artifact@v3
        with:
          name: HesapMakinesiAPK
          path: ./*.apk
