name: APK Oluşturucu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Java ve Node Kur
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Bubblewrap Kur ve Ayarla
        run: |
          npm install -g @bubblewrap/cli
          mkdir -p ~/.bubblewrap
          # Yol tanımlamalarını yapıyoruz
          echo '{"jdkPath":"/usr/lib/jvm/java-17-openjdk-amd64","androidSdkPath":"/usr/local/lib/android/sdk"}' > ~/.bubblewrap/config.json

      - name: APK Paketle (Sessiz Mod)
        run: |
          # Bu komut tüm lisansları ve soruları otomatik 'evet' ile geçer
          yes | bubblewrap init --manifest=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/manifest.json --now
          yes | bubblewrap build --skipSigning
          
      - name: APK Dosyasını Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: HesapMakinesiAPK
          path: ./*.apk
